### ISSUE TITLE
Class error. Empty response

### ISSUE THREAD

**Issue by eqMFqfFd** [pavel-grom/php-minecraft-pe-query#1]

**Comment by jasonw4331** [comment]
That means that your other pocketmine server has query turned off or that it's offline. Another issue could be that you have the wrong ip address.

**Comment by kenygamer** [comment]
Tried with following IPS:
play.leet.cc : 19132
play.lbsg.net : 19132
fallentech.tk : 19132
survivaltimepe.leet.cc : 30598
None worked, query is ON, could you try querying some of these servers ?

**Comment by jasonw4331** [comment]
The checked ones worked:
 - [ ] play.leet.cc : 19132
 - [x] play.lbsg.net : 19132
 - [x] fallentech.tk : 19132
 - [x] survivaltimepe.leet.cc : 30598

Try adjusting your timeout

**Comment by pavel-grom** [comment]
https://minecraft-statistic.net/en/server/176.9.144.136_19132.html
play.leet.cc:19132 is offline for a long time
